---

- name: Deploy Alex Smith web site
  hosts: all
  become: yes
  tasks:
    - name: Download the folder 
      get_url:
        url: https://github.com/utrains/static-resume/archive/refs/heads/main.zip 
        dest: /tmp/main.zip    
    - name: Unzip Alex smith    
      unarchive:
        src: /tmp/main.zip
        dest: /tmp
        remote_src: yes
      when: ansible_os_family=="RedHat"  
    - name: Install httpd     
      package:
        name: httpd
        state: present
      when: ansible_os_family=="RedHat"  
    - name: Copy the unzip file to web server apache
      copy:
        src: /tmp/static-resume-main/
        dest: /var/www/html/
        remote_src: yes
      when: ansible_os_family=="RedHat"  
    - name: Start apache server
      service:
        name: httpd
        state: started
      when: ansible_os_family=="RedHat"