---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: absent
        update_cache: yes
      when:  ansible_os_family=="Debian"
      tags: nginx_service

    - name: Install apache on redhat family
      package:
        name: httpd
        state: present
      when: ansible_os_family=="RedHat"
      tags: apache_service

    - name: Check if httpd service  exist
      stat:
        path: /usr/sbin/httpd
      register: httpd_stat
      when: ansible_os_family=="RedHat"
      tags: check_httpd

    - name: Start httpd daemon
      service: 
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family=="RedHat" and httpd_stat.stat.exists
      tags: start_daemon

    - name: Create user serge
      user:
        name: Rivelino
        comment: Rivelino Smith
        shell: /bin/bash
    - name: create group
      group:
        name: cloudteam
        state: present
    - name: create index file
      file:
        path: /var/www/html/index.html
        state: touch
    - name: Create directory
      file:
        path: /tmp/os
        state: directory
    
    - name : Copy content to index
      copy:
        dest: /var/www/html/index.html
        content: '<h1>This is created using ansible</h1>'