---
- hosts: ws
  become: yes

  tasks:
      
    - name: Install packages
      yum:
        name:
          - lsof
          - wget
          - passwd
          - docker
          - unzip
          - java-11
        state: present

    - name: Create directory 
      file:
        path: /opt/qa/spg
        state: directory
       
    - name: Create file
      file:
        path: /opt/qa/spg/spg.log
        state: touch

    - name: Start Docker service
      systemd:
        name: docker
        state: started

    - name: Enable Docker daemon
      systemd:
        name: docker
        enabled: yes